"""widen uuid columns to 100

Revision ID: 776fc558b80e
Revises: 84f323944eb4
Create Date: 2026-04-10 02:01:08.201162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776fc558b80e'
down_revision: Union[str, Sequence[str], None] = '84f323944eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dentists', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('orders', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('orders', 'patient_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('orders', 'dentist_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('originators', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('patients', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('restorations', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('submissions', 'ids_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('submissions', 'submission_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('uploaded_files', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('submissions', 'submission_uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('submissions', 'ids_uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('restorations', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('patients', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('originators', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'dentist_uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('orders', 'patient_uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('orders', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('dentists', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
